### ISSUE TITLE
Request for new feature in order to move tables for better relations reading

### ISSUE THREAD

**Issue by Alan-Graton** [AbianS/prisma-generate-uml#11]
First of all... loving this extension so far ^-^

Not a big problem, but it'd be nice to be able to move the tables in order to read the relations better. Tried sorting my models in prisma schema but it didn't do much ;-;

![image](https://github.com/user-attachments/assets/e3f453d9-ba20-4733-bed1-3c2886469111)

**Comment by AbianS** [comment]
First of all, I'm glad to hear that you like the extension! ^-^

Currently, I use Mermaid 9.3.0 to generate the diagrams, and Mermaid handles the rendering automatically. As far as I know, it doesn't allow for manual movement of elements or changing their positions. For that functionality, another library or a custom solution would be needed.

**Comment by Alan-Graton** [comment]
Ohhh I see. Just checked Mermaid plataform and you can't move cards from there as well ;-; Alrighty then, as I said not a big problem, I'll keep using this extension cause it been helping a lot ^-^

Do you want me to close this issue?

**Comment by AbianS** [comment]
Yes, I'll go ahead and close the issue since I have opened the discussion panel and added this as an idea to look into in the future. Thank you for your feedback and for using the extension! 😊
