### ISSUE TITLE
Prisma schema UML reopens after small changes

### ISSUE THREAD

**Issue by TheRedRacing** [AbianS/prisma-generate-uml#21]
Hi, I noticed the new pull request you created ([#20](https://github.com/AbianS/prisma-generate-uml/pull/20))—great work!

However, I encountered an issue while working on my Prisma schema file. If the schema UML is closed and I make a small change in it (e.g., adding a new line or modifying a model), the schema automatically reopens. This behavior can be disruptive, especially when I intentionally closed the schema.

Would it be possible to address this? Thank you!

https://github.com/user-attachments/assets/3af561a8-9f95-4793-bd3d-614cfce7410e

**Comment by AbianS** [comment]
Hi! Thanks for pointing that out.

I looked into the issue, and it’s now fixed. The panel will only update if it’s already open.

Thanks again for taking the time to report it. 😊
