### ISSUE TITLE
CPU usage is too high

### ISSUE THREAD

**Issue by wxs77577** [AbianS/prisma-generate-uml#23]
When I preview Prisma Schema UML：
<img width="535" alt="image" src="https://github.com/user-attachments/assets/e6a634f0-9657-4541-8764-6925a8fc177b" />

when i close preview：
<img width="530" alt="image" src="https://github.com/user-attachments/assets/28e06381-e84f-4b61-bd3e-80d53d915984" />

Could you please open some settings? For example, should animation or some rendering parameters be turned on?

**Comment by AbianS** [comment]
Thanks so much for letting me know about the issue! I’ll take a look as soon as I get a chance to see if I can optimize CPU usage a bit. I’ll also check if I can add some options to tweak performance, allowing you to turn features on or off as needed. Really appreciate you bringing this up! 😊

**Comment by AbianS** [comment]
Hi @wxs77577,

I’ve made several optimizations that should significantly reduce CPU usage.

Please give it a try and let me know how it works for you!

Thanks! 😊
